# Generated by Django 4.2.6 on 2023-11-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='timie',
            new_name='time',
        ),
    ]
