# Generated by Django 4.2.6 on 2023-11-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_rename_timie_data_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='h_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='temp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
