# Generated by Django 4.2.6 on 2023-11-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_data_h_total_data_temp_alter_data_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='h_total',
            new_name='H_Total',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='temp',
            new_name='Temp',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='time',
            new_name='Time',
        ),
    ]
