# Generated by Django 4.2.6 on 2023-11-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_rename_h_total_data_h_total_rename_temp_data_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='E_Today',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='E_Total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='Fac',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='Iac1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='Iac2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='Iac3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='Ipv1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='Ipv2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='Pac',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='SN',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='data',
            name='Vac1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='Vac2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='Vac3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='Vpv1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='Vpv2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='time_of_day',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='H_Total',
            field=models.IntegerField(default=0),
        ),
    ]
