# Generated by Django 4.2.6 on 2023-11-16 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charts', '0006_data_e_today_data_e_total_data_fac_data_iac1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
